languageCode = "cn-zh"
title = "河马的池塘"
baseURL = "http://pool.idyi.net"
theme="mainroad"
#ignoreFiles = [ "\\.foo"]
googleAnalytics = "UA-92973579-1"
disqusShortname = "hippool"
author = "Hippo"
copyright = "Copyright (c) 2017, Hippo; all rights reserved."
canonifyurls = true
paginate = 10

[permalinks]
    post = "/:year/:month/:slug/"
    page = "/:slug/"

#[taxonomies]
#    tag = "tags"
#    category = "categories"

[Author]
    name = "John Doe"
    bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
    avatar = "img/avatar.png"

[Params]
    subtitle = "Just another site" # Subtitle of your site
    description = "河马的笔记"
    opengraph = true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true

[[menu.main]]
    name = "ABOUT ME"
    pre = "<i class='fa fa-info-circle'></i>"
    weight = 0
    identifier = "about"
    url = "/page/about"

[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 10 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)


