languageCode = "cn-zh"
title = "河马的池塘"
baseURL = "http://pool.idyi.net/"
theme="mainroad"
#ignoreFiles = [ "\\.foo"]
googleAnalytics = "UA-92973579-1"
disqusShortname = "hippool"
author = "Hippo"
copyright = "Copyright (c) 2014-2017, Hippo; all rights reserved."
canonifyurls = true
paginate = 15

[permalinks]
    post = "/:year/:month/:slug/"
    page = "/:slug/"

#[taxonomies]
#    tag = "tags"
#    category = "categories"

[Author]
    name = "Hippo"
    bio = "Hippo's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
    avatar = "img/avatar.jpg"

[Params]
    subtitle = "一些技术笔记" # Subtitle of your site
    description = "河马的笔记"
    opengraph = true
#    leftsidebar = false # Move sidebar to the left side if true
    readmore = true # Show "Read more" button in list if true
    authorbox = true
    post_navigation = true
    toc = true # Enable Table of Contents
    pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
    post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
#    mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
    dateformat = "2006-01-02" # Change the format of dates

[Params.thumbnail]
    visibility = ["list", "post"] # Control thumbnail visibility

[Params.sidebar]
    home = "right" # Configure layout for home page
    list = "left"  # Configure layout for list pages
    single = false # Configure layout for single pages
    # Enable widgets in given order
    widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
    recent_num = 5 # Set the number of articles in the "Recent articles" widget
    categories_counter = true # Enable counter for each category in "Categories" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget
    
[[menu.main]]
    name = "ABOUT ME"
    pre = "<i class='fa fa-info-circle'></i>"
    weight = 0
    identifier = "about"
    url = "/about"

